# Generated by Django 5.2.12 on 2026-03-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('Élevée', 'Élevée'), ('Moyenne', 'Moyenne'), ('Petite', 'Petite'), ('Inconnue', 'Inconnue')], default='Inconnue', max_length=50)),
                ('ai_severity', models.CharField(choices=[('Élevée', 'Élevée'), ('Moyenne', 'Moyenne'), ('Petite', 'Petite'), ('Inconnue', 'Inconnue')], default='Inconnue', max_length=50)),
                ('technician', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Signalé', 'Signalé'), ('En cours', 'En cours'), ('Réparé', 'Réparé')], default='Signalé', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fuite',
                'verbose_name_plural': 'Fuites',
                'db_table': 'leaks',
            },
        ),
    ]
