# Generated by Django 5.2.12 on 2026-03-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_incident_delete_leak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='incident',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/'),
        ),
    ]
