# Generated by Django 5.2.12 on 2026-03-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_incident_photo_path_incident_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Libre', 'Libre'), ('En mission', 'En mission')], default='Libre', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('missions_completed', models.IntegerField(default=0)),
                ('avatar_color', models.CharField(default='var(--accent-orange)', max_length=50)),
            ],
            options={
                'verbose_name': 'Technicien',
                'verbose_name_plural': 'Techniciens',
                'db_table': 'technicians',
            },
        ),
    ]
