# Generated by Django 5.2.12 on 2026-03-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='category',
            field=models.CharField(choices=[('Eau', "Fuite d'eau"), ('Accident', 'Accident de la route'), ('Electricité', 'Court-circuit / Panne')], default='Eau', max_length=50),
        ),
    ]
