# Generated by Django 5.2.12 on 2026-03-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_technician_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='technician',
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='dashboard.technician'),
        ),
        migrations.AddField(
            model_name='technician',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Latitude du local ou de la ville de l'équipe", null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Longitude du local ou de la ville de l'équipe", null=True),
        ),
    ]
