# Generated by Django 5.2.12 on 2026-03-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_incident_technician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='email',
            field=models.EmailField(blank=True, help_text="Email de l'équipe pour recevoir les alertes", max_length=254, null=True),
        ),
    ]
