# Generated by Django 5.2.12 on 2026-03-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_technician_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
