# Generated by Django 5.2.12 on 2026-03-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('Eau', "Fuite d'eau"), ('Accident', 'Accident de la route'), ('Electricité', 'Court-circuit / Panne'), ('Telegram', 'Signalement Telegram')], default='Eau', max_length=50),
        ),
    ]
