# Generated by Django 4.2.11 on 2026-04-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_telegramuser_phone_number_alter_incident_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
